### ISSUE TITLE
Dashboard: Allow game creation

### ISSUE THREAD

**Issue by GVenzk** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_010#4]
As a customer, I want players to be able to create new games, because I want the players to be able to choose what server they play the game on.

Clicking the "create game" button that will add a new game to the list; the user will be allowed to set the game title and various other settings.

When clicking on the game from the list on the dashboard, the grid page will come up. Each grid cell adjacent to your character can be clicked to move and go to a different "game event" (some scene, a monster appears, etc).

**Comment by mechabubba** [comment]
some vagueness here; this issue used to be more involved with the dashboard listing of games, so it was changed a bit. more discussion is necessary to discern what information and action game creation entails.
